name: Update IP List

on:
  schedule:
    - cron: '0 */3 * * *' # 每3小时运行一次
  workflow_dispatch: # 允许手动触发
  push: # 允许提交触发

permissions:
  contents: write  # 关键：允许 GITHUB_TOKEN 拥有写权限

jobs:
  update-ip-list:
    runs-on: ubuntu-latest

    steps:
      # 使用 GITHUB_TOKEN 拉取代码，确保有写权限
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      # 第一个脚本
      - name: Run collect_ips.py
        run: |
          echo "=== 开始执行 collect_ips.py ==="
          python ${{ github.workspace }}/collect_ips.py
          echo "=== collect_ips.py 执行完毕 ==="

      # 第二个脚本
      - name: Run collect_ips_old.py
        run: |
          echo "=== 开始执行 collect_ips_old.py ==="
          python ${{ github.workspace }}/collect_ips_old.py
          echo "=== collect_ips_old.py 执行完毕 ==="

      - name: Commit and push changes
        run: |
          git config --global user.email "tianshideyou@proton.me"
          git config --global user.name "tianshipapa"
          if [ -n "$(git status --porcelain)" ]; then
            git add ip.txt
            git commit -m "Automatic update"
            git push
          else
            echo "No changes detected, skipping commit."
          fi
